Resources:
  ResidentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.residentsTable}
      AttributeDefinitions:
        - AttributeName: residentId
          AttributeType: S
      KeySchema:
        - AttributeName: residentId
          KeyType: HASH
      # Set the capacity based on the stage
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}
  # OtherTable:
  #   Type: AWS::DynamoDB::Table
  #   Properties:
  #     TableName: ${self:custom.otherTable}
  #     AttributeDefinitions:
  #       - AttributeName: residentId
  #         AttributeType: S
  #     KeySchema:
  #       - AttributeName: residentId
  #         KeyType: HASH
  #     # Set the capacity based on the stage
  #     ProvisionedThroughput:
  #       ReadCapacityUnits: ${self:custom.tableThroughput}
  #       WriteCapacityUnits: ${self:custom.tableThroughput}
