Resources:
  ResidentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.residentsTable}
      AttributeDefinitions:
        - AttributeName: residentId
<<<<<<< HEAD
          AttributeType: S
      KeySchema:
        - AttributeName: residentId
=======
          AttributeType: S
      KeySchema:
        - AttributeName: residentId
          KeyType: HASH
      # Set the capacity based on the stage
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}
  ApartsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.apartsTable}
      AttributeDefinitions:
        - AttributeName: apartId
          AttributeType: S
      KeySchema:
        - AttributeName: apartId
>>>>>>> 56a193b4b8faeacaca846281d1855d8fc7b7025f
          KeyType: HASH
      # Set the capacity based on the stage
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}
<<<<<<< HEAD
  # OtherTable:
  #   Type: AWS::DynamoDB::Table
  #   Properties:
  #     TableName: ${self:custom.otherTable}
  #     AttributeDefinitions:
  #       - AttributeName: residentId
  #         AttributeType: S
  #     KeySchema:
  #       - AttributeName: residentId
  #         KeyType: HASH
  #     # Set the capacity based on the stage
  #     ProvisionedThroughput:
  #       ReadCapacityUnits: ${self:custom.tableThroughput}
  #       WriteCapacityUnits: ${self:custom.tableThroughput}
=======
  MaintanancesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.maintanancesTable}
      AttributeDefinitions:
        - AttributeName: requestId
          AttributeType: S
      KeySchema:
        - AttributeName: requestId
          KeyType: HASH
      # Set the capacity based on the stage
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}
>>>>>>> 56a193b4b8faeacaca846281d1855d8fc7b7025f
